# config/app.yml for rails-settings-cached
defaults: &defaults
  email_from: "booksearch@library.yorku.ca"
  email_new_ticket_subject: "New Search Ticket Created"
  email_new_ticket_body: "New Search Ticket Has been created"
  email_ticket_resolved_subject: "Your Search Ticket Has Been Resolved"
  email_ticket_resolved_body: "Ticket resolved"
  legal_terms_of_use_title: "Terms of Use Title"
  legal_terms_of_use_body: "Terms of Use Body"    

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
